apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  annotations:
    trait.camel.apache.org/jolokia.enabled: 'true'
    trait.camel.apache.org/jolokia.protocol: https
  name: amqp-to-kafka
  namespace: kamelet-error-handling
spec:
  errorHandler:
    dead-letter-channel:
      endpoint:
        properties:
          destinationName: errorqueue
          destinationType: queue
          remoteURI: 'amqp://ex-aao-amqp-0-svc:5672'
        ref:
          apiVersion: camel.apache.org/v1alpha1
          kind: Kamelet
          name: jms-amqp-10-sink
  sink:
    properties:
      url: 'https://dummy-url/rest'
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: http-sink
  source:
    properties:
      destinationName: sourcequeue
      destinationType: queue
      remoteURI: 'amqp://ex-aao-amqp-0-svc:5672'
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: jms-amqp-10-source